# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-paginate
title: Brume
author: Aigars Dzerviniks
description: It's simple. It's easy to use. It's a Jekyll theme.

highlighter: null

url: https://huatrung.github.io/
baseurl: 


# Pagination Settings
paginate: 5
paginate_path: "/page/:num/"


# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado

# Site navigation
paths:
  home: /
  work: /categories/work/
  life: /categories/life/
  fun: /categories/fun/
  convexhull: /algorithm/geometry/convex-hull/